import { AI_MODEL } from "../../model";
import { AIResponseV3 } from "../../type_registry";
import { ModelMessage } from "./aisdk_types";

export type AIChatProfileProcessedMessageData = {
    /** A summarized version of this message */
    summarized?: any;
}

export type RawAIChatProfileMessage = (ModelMessage & { etc?: AIChatProfileProcessedMessageData });

export type AIChatProfileDisplayEntity = {
    name?: string;
    avatarUrl?: string;
}

export type BaseUserResponseMetadata = {
    /** Epoch time for when this happened */
    timestamp: number;
}

export type AIChatDialogueAdditional = {
    from: "assistant" | "user";
} & AIChatProfileDisplayEntity;

export type AIChatDialogueMessage = ((AIResponseV3 & AIChatDialogueAdditional) | ({ type: "message", payload: { message: string }, metadata: BaseUserResponseMetadata } & AIChatDialogueAdditional));

export type AIChatProfile = {
    settings: {
        /** The AI model to use */
        model?: AI_MODEL,
        /** The profile's system prompt */
        system?: string,
        /** The location where this chat is taking place, e.g discord, brain, discord_agent, etc. Used for logging purposes */
        location?: string,
        /** The temperature of the AI, 0 to 1 */
        temperature?: number,
        /** 
         * The instructions that appears due to the current location, e.g website might have 'use markdown' while discord might have 'use discord formatting' 
         * It's simply appended to the system prompt later, the reason it's seperate is because the location instructions can change for the same chat over time
        **/
        locationInstructions?: string,
        /** The chat's title */
        title?: string,
        /** Whether to disable auto title generation */
        disableAutoTitle?: boolean,
        /** Enable token-caching */
        tokenCaching?: boolean,
    },
    /** Summary information for this conversation */
    summary?: {
        /** Very short summary, like a single sentence */
        shortSummary?: string;
        /** Longer summmary, few sentences */
        longSummary?: string;
    }
    /** The raw dialogue messages */
    messages: RawAIChatProfileMessage[],
    /** The user's prompt and the responses generated by the AI model and sent to the user */
    dialogue: AIChatDialogueMessage[],

    /** Overwrite the default user's name and avatar, useful if the messages was sent on the user's behalf by a different entity */
    defaultDisplayUser?: AIChatProfileDisplayEntity,
    /** Overwrite the default AI's name and avatar, useful if the messages was sent on the AI's behalf by a different entity */
    defaultDisplayAssistant?: AIChatProfileDisplayEntity,
}

export interface ConversationV2 {
    version: "2.0"
    conversationId: string
    ownerUserId: string

    /** Whether to disable the ability for the user to view this conversation */
    disableView?: boolean

    profile: AIChatProfile
}